name: Release Binaries

on:
  push:
    tags:
      - '[0-9][0-9][0-9][0-9].*'

jobs:
  releases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Build Binary
        run: |
          make framjet-webhook-middleman TARGET_OS=${{ matrix.os }} TARGET_ARCH=${{ matrix.arch }}
          
          # Create archive for the binary
          if [ "${{ matrix.os }}" = "windows" ]; then
            zip "framjet-webhook-middleman-${{ matrix.os }}-${{ matrix.arch }}.zip" framjet-webhook-middleman.exe
          else
            tar czf "framjet-webhook-middleman-${{ matrix.os }}-${{ matrix.arch }}.tar.gz" framjet-webhook-middleman
          fi

      - name: Upload Release Binary
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            framjet-webhook-middleman-${{ matrix.os }}-${{ matrix.arch }}.*